# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sXskZ12OF8CtvO1EWJEPyJGLsRAnMkr
"""

print("Hola Alan")

import pandas as pd
import matplotlib.pyplot as plt

data = {
    "tipo_incidente": ["Incendios", "Rescates", "Accidentes", "Falsas Alarmas"],
    "cantidad": [73886, 26921, 21949, 2545]
}

df = pd.DataFrame(data)

df["porcentaje"] = (df["cantidad"] / df["cantidad"].sum()) * 100

print(df)

df.plot(x="tipo_incidente", y="cantidad", kind="bar")
plt.title("Cantidad de incidentes - RUBA 2023")
plt.show()

print("Promedio:", df["cantidad"].mean())